language: c

matrix:
  include:
    - os: linux
      compiler: clang-6.0
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - cmake
            - libhidapi-dev
            - libssl-dev
      script: /bin/sh -eux .travis/build-linux-clang
    - os: linux
      compiler: gcc-7
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - cmake
            - libhidapi-dev
            - libssl-dev
      script: /bin/sh -eux .travis/build-linux-gcc
    - os: linux
      compiler: i686-w64-mingw32-gcc-4.8
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - binutils-mingw-w64-i686
            - gcc-mingw-w64
            - g++-mingw-w64
            - mingw-w64-i686-dev
            - cmake
      script: /bin/sh -eux .travis/build-linux-mingw
    - os: osx
      osx_image: xcode9.3
      compiler: clang
      sudo: required
      script: /bin/sh -eux .travis/build-osx-clang

notifications:
  email: false
